services:
  backend:
    image: dsclregistry.azurecr.io/backend:latest
    container_name: dscl-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///challenges.db
      - CORS_ORIGINS=https://dscl.azurewebsites.net
      - PORT=5000
      - FLASK_AUTO_CREATE_TABLES=true
    restart: unless-stopped

  frontend:
    image: dsclregistry.azurecr.io/frontend:latest
    container_name: dscl-frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
